import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter=Inter({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        >
        <Header/>
        <main className="min-h-screen px-4 md:px-8 max-w-7xl mx-auto py-6 mt-20">
          {children}
        </main>
      <Footer/>
      </body>
    </html>
  );
}
